version: "3.8"

services:
  app:
    build: 
     context: .
     dockerfile: Dockerfile
    #container_name: hitman-compose-container
    ports:
      - "9092:8086"
    environment:
      MYSQL_HOST: mysql           
      MYSQL_PORT: 3306            
      MYSQL_USER: root            
      MYSQL_PASSWORD: sanjan@root        
      MYSQL_DB_NAME: hitman
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest         
    #container_name: mysql-compose-container
    ports:
      - "3307:3306"         
    environment:
      MYSQL_ROOT_PASSWORD: sanjan@root
      MYSQL_DATABASE: hitman              
    volumes:
      - db_data:/var/lib/mysql
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s
     

volumes:
  db_data:

